
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DRINK ICE LEVEL NUMBER PERCENT SIZE SUGARorder : DRINK optionoption : NUMBER Toption SIZE \n    | NUMBER SIZE Toption \n    | Toption NUMBER SIZE\n    | Toption SIZE NUMBER\n    | SIZE NUMBER Toption\n    | SIZE Toption NUMBERToption : Setlevel SUGAR Setlevel ICE\n                | Setlevel ICE Setlevel SUGARSetlevel : level\n                | PERCENTlevel : LEVEL'
    
_lr_action_items = {'DRINK':([0,],[2,]),'$end':([1,3,19,20,21,22,23,24,27,28,],[0,-1,-2,-3,-4,-5,-6,-7,-8,-9,]),'NUMBER':([2,5,6,14,16,27,28,],[4,13,15,22,24,-8,-9,]),'SIZE':([2,4,5,11,13,27,28,],[6,12,14,19,21,-8,-9,]),'PERCENT':([2,4,6,12,15,17,18,],[9,9,9,9,9,9,9,]),'LEVEL':([2,4,6,12,15,17,18,],[10,10,10,10,10,10,10,]),'SUGAR':([7,8,9,10,26,],[17,-10,-11,-12,28,]),'ICE':([7,8,9,10,25,],[18,-10,-11,-12,27,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'order':([0,],[1,]),'option':([2,],[3,]),'Toption':([2,4,6,12,15,],[5,11,16,20,23,]),'Setlevel':([2,4,6,12,15,17,18,],[7,7,7,7,7,25,26,]),'level':([2,4,6,12,15,17,18,],[8,8,8,8,8,8,8,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> order","S'",1,None,None,None),
  ('order -> DRINK option','order',2,'p_order','yacc_easy_example.py',12),
  ('option -> NUMBER Toption SIZE','option',3,'p_option','yacc_easy_example.py',16),
  ('option -> NUMBER SIZE Toption','option',3,'p_option','yacc_easy_example.py',17),
  ('option -> Toption NUMBER SIZE','option',3,'p_option','yacc_easy_example.py',18),
  ('option -> Toption SIZE NUMBER','option',3,'p_option','yacc_easy_example.py',19),
  ('option -> SIZE NUMBER Toption','option',3,'p_option','yacc_easy_example.py',20),
  ('option -> SIZE Toption NUMBER','option',3,'p_option','yacc_easy_example.py',21),
  ('Toption -> Setlevel SUGAR Setlevel ICE','Toption',4,'p_Toption','yacc_easy_example.py',36),
  ('Toption -> Setlevel ICE Setlevel SUGAR','Toption',4,'p_Toption','yacc_easy_example.py',37),
  ('Setlevel -> level','Setlevel',1,'p_Setlevel','yacc_easy_example.py',45),
  ('Setlevel -> PERCENT','Setlevel',1,'p_Setlevel','yacc_easy_example.py',46),
  ('level -> LEVEL','level',1,'p_level','yacc_easy_example.py',51),
]
